# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liseapp', '0002_auto_20171115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2017, 12, 8)),
        ),
    ]
