# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liseapp', '0011_auto_20171215_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 0, 40, 3, 804575)),
        ),
    ]
