# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liseapp', '0012_auto_20171216_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 0, 48, 0, 669167)),
        ),
    ]
