# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liseapp', '0015_auto_20171216_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 1, 20, 24, 63844, tzinfo=utc)),
        ),
    ]
