# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='managedata.CategoryBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_pt', models.CharField(max_length=500)),
                ('text_en', models.CharField(max_length=500)),
                ('polality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50)),
                ('complete_text', models.CharField(max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='managedata.Business')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=240)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='managedata.Opinion')),
                ('relations_topics', models.ManyToManyField(related_name='_topic_relations_topics_+', to='managedata.topic')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyBusinessPlan',
            fields=[
                ('businessplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='managedata.BusinessPlan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_business_plans', to='managedata.CategoryBusiness')),
            ],
            bases=('managedata.businessplan',),
        ),
        migrations.CreateModel(
            name='LateBusinessPlan',
            fields=[
                ('businessplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='managedata.BusinessPlan')),
            ],
            bases=('managedata.businessplan',),
        ),
        migrations.AddField(
            model_name='opinion',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='managedata.Review'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_business', to='managedata.CategoryBusiness'),
        ),
        migrations.AddField(
            model_name='latebusinessplan',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_business_plan', to='managedata.Business'),
        ),
    ]
