# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='relations_topics',
            field=models.ManyToManyField(related_name='_topic_relations_topics_+', to='managedata.Topic'),
        ),
    ]
