# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0002_auto_20170929_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='topics',
            field=models.ManyToManyField(blank=True, to='managedata.Topic'),
        ),
    ]
