# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0003_auto_20171002_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earlybusinessplan',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='latebusinessplan',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='earlybusinessplan',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latebusinessplan',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
