# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0004_auto_20171115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlybusinessplan',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='latebusinessplan',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
