# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0005_auto_20171115_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=240)),
                ('branch', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('aceita', models.BooleanField(default=True)),
            ],
        ),
    ]
