# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0006_requestcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcategory',
            old_name='aceita',
            new_name='accept',
        ),
    ]
