# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0007_auto_20171115_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earlybusinessplan',
            name='done',
        ),
        migrations.RemoveField(
            model_name='latebusinessplan',
            name='done',
        ),
        migrations.AlterField(
            model_name='earlybusinessplan',
            name='state',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15),
        ),
        migrations.AlterField(
            model_name='latebusinessplan',
            name='state',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15),
        ),
    ]
