# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0008_auto_20171116_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlybusinessplan',
            name='status',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15),
        ),
        migrations.AddField(
            model_name='latebusinessplan',
            name='status',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15),
        ),
        migrations.AlterField(
            model_name='earlybusinessplan',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='latebusinessplan',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
