# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0009_auto_20171116_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlybusinessplan',
            name='enterprising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedata.Enterprising'),
        ),
        migrations.AlterField(
            model_name='latebusinessplan',
            name='enterprising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedata.Enterprising'),
        ),
    ]
