# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0011_requestcategory_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateField(),
        ),
    ]
