# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0012_auto_20171121_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcategory',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
