# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0013_auto_20171121_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcategory',
            name='accept',
        ),
        migrations.AddField(
            model_name='requestcategory',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=8),
        ),
    ]
