# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0014_auto_20171122_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcategory',
            name='enterprising',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='managedata.Enterprising'),
            preserve_default=False,
        ),
    ]
