# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0015_requestcategory_enterprising'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='earlybusinessplan',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15),
        ),
        migrations.AlterField(
            model_name='latebusinessplan',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15),
        ),
        migrations.AddField(
            model_name='dataupdate',
            name='plans',
            field=models.ManyToManyField(to='managedata.EarlyBusinessPlan'),
        ),
    ]
