# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0016_auto_20171123_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupdate',
            options={'ordering': ['-numero']},
        ),
        migrations.AddField(
            model_name='itemtopic',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('ativo', 'Ativo'), ('recusado', 'Recusado')], default='ativo', max_length=20),
        ),
    ]
