# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0019_auto_20171126_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtopic',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('ativo', 'Ativo'), ('recusado', 'Recusado')], default='novo', max_length=20),
        ),
    ]
