# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0021_auto_20171126_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtopic',
            name='categories',
            field=models.ManyToManyField(to='managedata.CategoryBusiness'),
        ),
    ]
