# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0022_auto_20171126_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorybusiness',
            name='branch',
        ),
        migrations.AddField(
            model_name='categorybusiness',
            name='branch',
            field=models.ManyToManyField(to='managedata.Branch'),
        ),
    ]
