# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0023_auto_20171130_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='categorybusiness',
            name='specialty',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
