# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0025_auto_20171130_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
    ]
