# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0026_auto_20171130_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybusiness',
            options={},
        ),
    ]
