# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0027_auto_20171130_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to='managedata.CategoryBusiness')),
                ('enterprising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedata.Enterprising')),
            ],
        ),
        migrations.RemoveField(
            model_name='earlybusinessplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='latebusinessplan',
            name='business',
        ),
        migrations.RemoveField(
            model_name='latebusinessplan',
            name='enterprising',
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='plans',
            field=models.ManyToManyField(to='managedata.BusinessPlan'),
        ),
        migrations.DeleteModel(
            name='EarlyBusinessPlan',
        ),
        migrations.DeleteModel(
            name='LateBusinessPlan',
        ),
    ]
