# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0028_auto_20171201_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtopic',
            name='category_suggestion',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
