# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0029_itemtopic_category_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtopic',
            name='context',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemtopic',
            name='category_suggestion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
