# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0030_auto_20171202_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtopic',
            name='category_suggestion',
        ),
    ]
