# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0032_opinion_lemmatized'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcategory',
            name='reason_refuse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateField(default=datetime.date(2017, 12, 8)),
        ),
    ]
