# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0034_auto_20171208_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcategory',
            name='category_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestcategories', to='managedata.CategoryBusiness'),
        ),
    ]
