# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0035_requestcategory_category_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateField(default=datetime.date(2017, 12, 14)),
        ),
    ]
