# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0039_auto_20171214_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_collect',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateField(default=datetime.date(2017, 12, 15)),
        ),
    ]
