# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0040_auto_20171215_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtopic',
            old_name='noun',
            new_name='lemma',
        ),
        migrations.AddField(
            model_name='opinion',
            name='nouns',
            field=models.TextField(default=''),
        ),
    ]
