# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0042_auto_20171216_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_website',
            field=models.BooleanField(default=False),
        ),
    ]
