# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0044_auto_20171216_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 1, 20, 41, 73748, tzinfo=utc)),
        ),
    ]
