# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0045_auto_20171216_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='is_face',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_website',
        ),
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 17, 22, 37, 312275, tzinfo=utc)),
        ),
    ]
