# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0046_auto_20171216_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank='', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 17, 35, 43, 952525, tzinfo=utc)),
        ),
    ]
