# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0048_auto_20171216_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 0, 38, 31, 220615, tzinfo=utc)),
        ),
    ]
