# -*- coding: utf-8 -*-

"""
Django settings for Lise project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@qp-$%)-*dw9x$=b7i7-)b2e6wi8tzvy13=b%8dbyhigwt6-uv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'managedata',
    'liseapp',
    'django_q',
    'liseadmin',
]


Q_CLUSTER = {
    'redis': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'password': None,
        'socket_timeout': None,
        'charset': 'utf-8',
        'errors': 'strict',
        'unix_socket_path': None
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Lise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

GRAPH_MODELS  =  {
  'all_applications' :  False,
  'group_models' :  True
}



WSGI_APPLICATION = 'Lise.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # 'ENGINE': 'django.db.backends.mysql',
        # 'OPTIONS': {
        #     'read_default_file': os.path.join(BASE_DIR, 'my.cnf'),
        # },
    }
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'liseapp:index'

AUTHENTICATION_BACKENDS = ('liseapp.models.EmailBackend',)


# CONFIG JET
JET_DEFAULT_THEME = 'default'
#

JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True
JET_INDEX_DASHBOARD = 'liseadmin.dashboard.CustomIndexDashboard'
# JET_APP_INDEX_DASHBOARD  =  'jet.dashboard.dashboard.DefaultAppIndexDashboard'
JET_SIDE_MENU_ITEMS = [

    {'label': _('Controle'), 'items': [
        {'label': _('Solicitações de Categoria'), 'url': '/admin/request_categories/'},
        {'label': _('Categoria'), 'url': '/admin/manage_categories/'},
        {'label': _('Planos de Negócios'), 'url': '/admin/manage_plan/'},
        {'label': _('Tópicos'), 'url': '/admin/manage_topics/'},
    ]},
    {'label': _('Gerencimento de dados'), 'items': [
        {'label': _('Atualização'), 'url': '/admin/manage_data/'},
        {'label': _('Items dos Tópicos'), 'url': '/admin/new_items/'},
    ]},
    {'label': _('Usuários'), 'items': [
        {'name': 'auth.user'},
        {'name': 'auth.group'}
    ]},
    {'label': _('Modelos'), 'items': [
        {'name': 'managedata.branch'},
        {'name': 'managedata.business'},
        {'name': 'managedata.categorybusiness'},
        {'name': 'managedata.businessplan'},
        {'name': 'managedata.enterprising'},
        {'name': 'managedata.itemtopic'},
        {'name': 'managedata.keyword'},
        {'name': 'managedata.opinion'},
        {'name': 'managedata.requestcategory'},
        {'name': 'managedata.review'},
        {'name': 'managedata.topic'},
        {'name': 'managedata.weekday'},
        {'name': 'liseapp.notification'},

    ]},
]





